### ISSUE TITLE
Command failed: tsc -p ./tsconfig.json Unhandled promise rejection

### ISSUE THREAD

**Issue by Alynva** [justinlettau/react-undraw#39]
## Type
What kind of issue is this?

```
[x] Bug report.
[ ] Feature request.
```

## Current Behavior
The `react-undraw-cli` throw this:

> (node:5996) UnhandledPromiseRejectionWarning: Error: Command failed: tsc -p ./tsconfig.json
> (node:7172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Catching that error and logging it, the correct error was:

> src/undraw/Undraw.test.tsx(2,22): error TS7016: Could not find a declaration file for module \'react-dom\'. \'\<myproject\>/node_modules/react-dom/index.js\' implicitly has an \'any\' type.\r\n  Try `npm install @types/react-dom` if it exists or add a new declaration (.d.ts) file containing `declare module \'react-dom\';`\r\nsrc/undraw/Undraw.test.tsx(6,1): error TS2582: Cannot find name \'it\'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

## Expected behavior
At this point, it should generate the components, 

## Steps to Reproduce
- `mkdir react-undraw-issue`
- `cd react-undraw-issue`
- `npm i react-undraw@2.0.0-beta.1` (the error appears here too)
- add `"undraw": "react-undraw-cli",` in `scripts` of `package.json`
- `npm run undraw`

## Other Information
~After installing those `@types/...` in `_phantomChildren` field of `package.json` of your project, it creates the components as should.~
EDIT: idk any more what I did to make it work

**Comment by Alynva** [comment]
Moving these `@types/...` to `dependencies` instead of `devDependencies` fixed the problem: https://github.com/Alynva/react-undraw

**Comment by filipsuk** [comment]
@justinlettau I encoutered this problem in 2.0.0.

After I caught the error in scripts/build.js

```ts
try {
    await promiseExec('tsc -p ./tsconfig.json', { cwd: root });
  } catch (err) {
    console.error(err)
  }
```

this was the output

```
npm run build

> Investown@1.0.0 prebuild /Users/X/Development/Investown/investown-fe
> react-undraw-cli

Generating unDraw components ...
Component built: "UndrawAccessDenied"
Component built: "UndrawBankAccount"

Error: Command failed: tsc -p ./tsconfig.json

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tsc -p ./tsconfig.json',
  stdout: "../@types/react-native/globals.d.ts(40,15): error TS2300: Duplicate identifier 'FormData'.\n" +
    "../@types/react-native/globals.d.ts(85,5): error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined', but here has type 'string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | ... 8 more ... | undefined'.\n" +
    "../@types/react-native/globals.d.ts(94,5): error TS2717: Subsequent property declarations must have the same type.  Property 'signal' must be of type 'AbortSignal | null | undefined', but here has type 'AbortSignal | undefined'.\n" +
    "../@types/react-native/globals.d.ts(112,14): error TS2300: Duplicate identifier 'RequestInfo'.\n" +
    "../@types/react-native/globals.d.ts(131,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Response' must be of type '{ new (body?: string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error(): Response; redirect(url: string, status?: number | undefined): Response; }', but here has type '{ new (body?: string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | ... 8 more ... | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error: () => Response; redirect: (url: string, status?: number | undefined) => Response; }'.\n" +
...
```

The list goes much longer.

As a workaround adding `"skipLibCheck": true` your the library's tsconfig compiler options seems to do the trick.

**Comment by justinlettau** [comment]
Thanks @filipsuk. Looks like a conflict with react-native types. I'll try to check it out.

**Comment by alistairholt** [comment]
Still broken 🙁

**Comment by prebours** [comment]
Hello:

I confirm the issue on version `2.0.1`.

To replicate, from an empty directory:
`
npm init
npm install react-undraw`

Error:
```
> node ./scripts/build.js

Generating unDraw components ...
(node:20876) UnhandledPromiseRejectionWarning: Error: Command failed: tsc -p ./tsconfig.json

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:20876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-undraw@2.0.1 requires a peer of react@^16.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-undraw@2.0.1 requires a peer of react-dom@^16.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN undraw-test@1.0.0 No description
npm WARN undraw-test@1.0.0 No repository field.

+ react-undraw@2.0.1
added 226 packages from 266 contributors and audited 226 packages in 15.258s

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by marklawlor** [comment]
@justinlettau I've added a PR to add to skipLibCheck option to tsconfig. Since this library bundles types as production dependencies you will run into conflicts over time, so skipping the type check is the best solution.

If you want to keep `skipLibCheck` for development, its probably better to have two config files, eg `tsconfig.json` & `tsconfig.production.json`

**Comment by filipsuk** [comment]
@justinlettau could you please release new version with this this fix?

**Comment by Alynva** [comment]
I'm still having this issue, even with 2.0.3:

> react-undraw@2.0.3 postinstall /builds/nbssistemas/conpub/pwa/node_modules/react-undraw
> npm run build
> react-undraw@2.0.3 build /builds/nbssistemas/conpub/pwa/node_modules/react-undraw
> node ./scripts/build.js
> Generating unDraw components ...
> Component built: "UndrawBlankCanvas"
> Component built: "UndrawCompletedTasks"
> Component built: "UndrawEmpty"
> Component built: "UndrawFillForms"
> Component built: "UndrawFixingBugs"
> Component built: "UndrawMyPassword"
> Component built: "UndrawNoData"
> Component built: "UndrawPageNotFound"
> Component built: "UndrawPreferences"
> Component built: "UndrawQuiteTown"
> Component built: "UndrawServerDown"
> Component built: "UndrawServer"
> Component built: "UndrawThrowAway"
> (node:52) UnhandledPromiseRejectionWarning: Error: Command failed: tsc -p ./tsconfig.json
> /bin/sh: 1: tsc: not found
>     at ChildProcess.exithandler (child_process.js:294:12)
>     at ChildProcess.emit (events.js:198:13)
>     at maybeClose (internal/child_process.js:982:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> (node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:52) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I suggest use `npx tsc`...

**Comment by Alynva** [comment]
The command `tsc -p ./tsconfig.json` runs after the package being installed, so typescript it's not just a **dev**elopment dependency of this package. I don't know about the `@types/...` and the `skipLibCheck`, but having `typescript` in the `dependencies` worked for me and makes more sense.
