### ISSUE TITLE
Imported SVG are not rendering.

### ISSUE THREAD

**Issue by M4urici0GM** [justinlettau/react-undraw#40]
## BUG
```
[x] Bug report.
[] Feature request.
```

## Current Behavior
I Downloaded the svg file from undraw repo website, created a folder called ```undraw``` in the project root, renamed the svg to remove the suffix, prefix, and tried to render the svg with 
```jsx
 <Undraw
   name="signin"
 />
```
i've put the "react-undraw-cli" in start and build scripts.
The  svg is not rendering., nothing happens.

## Expected behavior
SVG being rendered.

## Steps to Reproduce
- Download the SVG that i've tried from [Undraw](https://undraw.co/illustrations)
- Create a folder inside the project root called undraw, and paste the file in there.
- Try to render it with the undraw component.

## Other Information
One fact is that i've tried to run ```yarn react-undraw-cli```, but it seems that the cli command is not working.
 - React version: 16.13.1
 - Using typescript 3.7.2

The project structure:
![image](https://user-images.githubusercontent.com/37017091/83358079-59092b00-a347-11ea-9b2f-a73178450224.png)

Pieces of code:
 - The component that i've trying to render the undraw svg
```jsx
const Signin: React.FC = () => {
    return (
        <div>
            <Undraw
                name="test"
            />
        </div>
    );
}
```
- My Scripts:
```json
  "scripts": {
    "start": "react-scripts start && react-undraw-cli",
    "build": "react-scripts build && react-undraw-cli",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "prebuild": "react-undraw-cli"
  },
```
The repo is actually public, that's an open source project, you can also check there if want to.

**Comment by justinlettau** [comment]
Can you confirm you have v2 installed?

```
npm i --save react-undraw@2.0.0-beta.1
```

You should see a log during your build that looks like this ..

![image](https://user-images.githubusercontent.com/5008151/83366308-0c334d80-a363-11ea-866b-d45ba542d4df.png)

**Comment by M4urici0GM** [comment]
Lol, it works
Thanks buddie
I recommend specifying in the docs which feature is compatible with the current version, i was pretty confused lol.
