### ISSUE TITLE
Add style and className props

### ISSUE THREAD

**Issue by jgoux** [justinlettau/react-undraw#5]
Hello,

## Type
What kind of issue is this?

```
[ ] Bug report.
[x] Feature request.
```

I'd like to apply extra styles to the svg illustration but there is no way to pass a className or style prop.

Is it possible to add them?

**Comment by justinlettau** [comment]
@jgoux With v1.4.0, any extra props (like `className`) used on the `<Undraw />` component will be passed onto the SVG element. 

Note: If you provide a `style` prop it will override the default (that specifies the height/width) style. You can re-add these manually with the style or CSS.

**Comment by jgoux** [comment]
The issue is that all the props are passed to the svg node, even `height` and `primaryColor` so we get warning from react, see here : https://github.com/justinlettau/react-undraw/blob/master/src/lib/undraw/Undraw.js#L54

Maybe you should compute a `style` object from these two props and pass it to the `Illustration` component?

**Comment by justinlettau** [comment]
@jgoux Yeah, I noticed the warning about the `primaryColor` prop. I'll get that fixed. Thanks.

**Comment by justinlettau** [comment]
@jgoux Warnings should be gone with v1.5.0!
