### ISSUE TITLE
Can't execute react-undraw-cli

### ISSUE THREAD

**Issue by DDeme** [justinlettau/react-undraw#53]
## Type
What kind of issue is this?

```
[x] Bug report.
[ ] Feature request.
```

## Current Behavior
Can't execute react-undraw-cli

I have manually write path  to .bin folder

## Steps to Reproduce
Install current version using yarn on Debian OS

**Comment by fnowacki** [comment]
Hi @DDeme, I fixed this in #55 👋

**Comment by jgoux** [comment]
@fnowacki Is it solved on your end after your change? We just installed react-undraw@2.0.3 and we are experiencing the exact same issue (on MacOS Big Sur).

**Comment by fnowacki** [comment]
@jgoux yeah, it worked for me but a few months ago I removed this library from my project because it was soooo slow. I decided to import directly svgs as ReactComponent.
